services:
  # PostgreSQL資料庫
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ptt_stock_crawler
      POSTGRES_USER: ptt_user
      POSTGRES_PASSWORD: ptt_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ptt_user -d ptt_stock_crawler"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PTT爬蟲應用程式
  crawler:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://ptt_user:ptt_password@localhost:5432/ptt_stock_crawler
      TARGET_AUTHORS: mrp
      CRAWL_INTERVAL: 300
      MCP_SERVER_HOST: 0.0.0.0
      MCP_SERVER_PORT: 8000
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
